#!/bin/bash
set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

debian/tests/jtreg-autopkgtest.sh jaxp -exclude:test/jaxp/ProblemList.txt -exclude:debian/failed-tests-problemlist.txt test/jaxp && jtreg_exit=0 || jtreg_exit=$?

[ $jtreg_exit -eq 77 ] && exit 77

debian/tests/jtdiff-autopkgtest.sh jaxp
